import os

APP_NAME = "Jyoti Cards ERP"
APP_PASSWORD = os.getenv("APP_PASSWORD", "kiwigudda")
BUSINESS_WHATSAPP_NUMBER = os.getenv("BUSINESS_WHATSAPP_NUMBER", "9516789702")
INTERNAL_ALERT_NUMBER = os.getenv("INTERNAL_ALERT_NUMBER", "9754656565")
META_ACCESS_TOKEN = os.getenv("META_ACCESS_TOKEN", "")
META_PHONE_NUMBER_ID = os.getenv("META_PHONE_NUMBER_ID", "")
META_BUSINESS_ACCOUNT_ID = os.getenv("META_BUSINESS_ACCOUNT_ID", "")
META_API_VERSION = os.getenv("META_API_VERSION", "v25.0")
WHATSAPP_PROVIDER = os.getenv("WHATSAPP_PROVIDER", "meta")
META_WEBHOOK_VERIFY_TOKEN = os.getenv("META_WEBHOOK_VERIFY_TOKEN", "jyoti_cards_wh_verify_2026")
META_WEBHOOK_PATH = os.getenv("META_WEBHOOK_PATH", "/webhooks/whatsapp")
META_WEBHOOK_PORT = int(os.getenv("META_WEBHOOK_PORT", os.getenv("PORT", "8080")))
