import os

APP_NAME = "Jyoti Cards ERP"
APP_PASSWORD = os.getenv("APP_PASSWORD", "kiwigudda")
BUSINESS_WHATSAPP_NUMBER = os.getenv("BUSINESS_WHATSAPP_NUMBER", "9516789702")
INTERNAL_ALERT_NUMBER = os.getenv("INTERNAL_ALERT_NUMBER", "9754656565")
META_ACCESS_TOKEN = os.getenv("META_ACCESS_TOKEN", "")
META_PHONE_NUMBER_ID = os.getenv("META_PHONE_NUMBER_ID", "")
META_BUSINESS_ACCOUNT_ID = os.getenv("META_BUSINESS_ACCOUNT_ID", "")
META_VERIFY_TOKEN = os.getenv("META_VERIFY_TOKEN", "jyoti-cards-verify")
META_API_VERSION = os.getenv("META_API_VERSION", "v20.0")
WHATSAPP_PROVIDER = os.getenv("WHATSAPP_PROVIDER", "mock")
PUBLIC_BACKEND_URL = os.getenv("PUBLIC_BACKEND_URL", "http://localhost:8015")
DAILY_REPORT_HOUR = int(os.getenv("DAILY_REPORT_HOUR", "20"))
