"""Latin party names and city names to Hindi, for the sticker print only."""
from __future__ import annotations

import re

# Trade words and names that a letter-by-letter reading would get wrong.
WORDS = {
    "aadhya": "आध्या",
    "aaditya": "आदित्य",
    "aashirwad": "आशीर्वाद",
    "aditya": "आदित्य",
    "advertising": "एडवर्टाइजिंग",
    "agency": "एजेंसी",
    "agrawal": "अग्रवाल",
    "agarwal": "अग्रवाल",
    "ajay": "अजय",
    "akshat": "अक्षत",
    "ambey": "अंबे",
    "ambe": "अंबे",
    "ambika": "अंबिका",
    "amit": "अमित",
    "anand": "आनंद",
    "and": "और",
    "anil": "अनिल",
    "ankit": "अंकित",
    "anmol": "अनमोल",
    "apex": "एपेक्स",
    "arihant": "अरिहंत",
    "art": "आर्ट",
    "arts": "आर्ट्स",
    "asha": "आशा",
    "ashirwad": "आशीर्वाद",
    "ashok": "अशोक",
    "baba": "बाबा",
    "badshah": "बादशाह",
    "bairagi": "बैरागी",
    "balaji": "बालाजी",
    "barman": "बर्मन",
    "bazar": "बाज़ार",
    "bazaar": "बाज़ार",
    "bhagat": "भगत",
    "bhai": "भाई",
    "bhairav": "भैरव",
    "bhaiya": "भैया",
    "bhandar": "भंडार",
    "bharat": "भारत",
    "bhavani": "भवानी",
    "bhawan": "भवन",
    "bhawsar": "भावसार",
    "bheru": "भैरू",
    "birsa": "बिरसा",
    "book": "बुक",
    "bros": "ब्रदर्स",
    "brothers": "ब्रदर्स",
    "bunty": "बंटी",
    "burhani": "बुर्हानी",
    "card": "कार्ड",
    "cards": "कार्ड्स",
    "centre": "सेंटर",
    "center": "सेंटर",
    "chamunda": "चामुंडा",
    "chand": "चंद",
    "choice": "चॉइस",
    "chouhan": "चौहान",
    "chourasiya": "चौरसिया",
    "co": "को",
    "collection": "कलेक्शन",
    "colours": "कलर्स",
    "colors": "कलर्स",
    "computer": "कम्प्यूटर",
    "computers": "कम्प्यूटर्स",
    "copy": "कॉपी",
    "creation": "क्रिएशन",
    "creative": "क्रिएटिव",
    "cyber": "साइबर",
    "das": "दास",
    "deep": "दीप",
    "deepak": "दीपक",
    "depo": "डिपो",
    "depot": "डिपो",
    "design": "डिज़ाइन",
    "dev": "देव",
    "dham": "धाम",
    "diamond": "डायमंड",
    "digital": "डिजिटल",
    "dinesh": "दिनेश",
    "divya": "दिव्या",
    "durga": "दुर्गा",
    "emporium": "एम्पोरियम",
    "enterprises": "एंटरप्राइजेज",
    "fancy": "फैंसी",
    "flex": "फ्लेक्स",
    "gallery": "गैलरी",
    "gandharvpuri": "गंधर्वपुरी",
    "ganesh": "गणेश",
    "garima": "गरिमा",
    "garphics": "ग्राफिक्स",
    "gayatri": "गायत्री",
    "geeta": "गीता",
    "general": "जनरल",
    "gift": "गिफ्ट",
    "gifts": "गिफ्ट्स",
    "goyal": "गोयल",
    "gram": "ग्राम",
    "graphic": "ग्राफिक",
    "graphics": "ग्राफिक्स",
    "gupta": "गुप्ता",
    "gurjar": "गुर्जर",
    "guru": "गुरु",
    "gurukripa": "गुरुकृपा",
    "hanuman": "हनुमान",
    "hari": "हरि",
    "harpal": "हरपाल",
    "harsh": "हर्ष",
    "himanshu": "हिमांशु",
    "hinglaj": "हिंगलाज",
    "hitesh": "हितेश",
    "house": "हाउस",
    "industries": "इंडस्ट्रीज",
    "industry": "इंडस्ट्री",
    "internet": "इंटरनेट",
    "jagdish": "जगदीश",
    "jai": "जय",
    "jain": "जैन",
    "jaiswal": "जायसवाल",
    "ji": "जी",
    "jitendra": "जितेंद्र",
    "johar": "जोहर",
    "jyoti": "ज्योति",
    "kalash": "कलश",
    "kali": "काली",
    "kamlesh": "कमलेश",
    "karyalaya": "कार्यालय",
    "kendra": "केंद्र",
    "khajrana": "खजराना",
    "khandelwal": "खंडेलवाल",
    "khatu": "खाटू",
    "khushi": "खुशी",
    "kirana": "किराना",
    "kripa": "कृपा",
    "krishna": "कृष्ण",
    "krupa": "कृपा",
    "kumar": "कुमार",
    "labh": "लाभ",
    "lakshmi": "लक्ष्मी",
    "lal": "लाल",
    "lalit": "ललित",
    "laxmi": "लक्ष्मी",
    "leela": "लीला",
    "llp": "एलएलपी",
    "lokesh": "लोकेश",
    "ltd": "लिमिटेड",
    "maa": "माँ",
    "mahalakshmi": "महालक्ष्मी",
    "mahalaxmi": "महालक्ष्मी",
    "mahendra": "महेंद्र",
    "mahaveer": "महावीर",
    "mahesh": "महेश",
    "maheshwari": "माहेश्वरी",
    "mahi": "माही",
    "mall": "मॉल",
    "mandir": "मंदिर",
    "mangalam": "मंगलम",
    "manoj": "मनोज",
    "mart": "मार्ट",
    "maruti": "मारुति",
    "mata": "माता",
    "mehta": "मेहता",
    "mobile": "मोबाइल",
    "mohit": "मोहित",
    "mudran": "मुद्रण",
    "mudranalay": "मुद्रणालय",
    "mukesh": "मुकेश",
    "nagar": "नगर",
    "nakoda": "नाकोड़ा",
    "naresh": "नरेश",
    "narmada": "नर्मदा",
    "natraj": "नटराज",
    "nataraj": "नटराज",
    "national": "नेशनल",
    "navrang": "नवरंग",
    "new": "न्यू",
    "nitin": "नितिन",
    "offset": "ऑफसेट",
    "om": "ॐ",
    "omkar": "ओंकार",
    "online": "ऑनलाइन",
    "palace": "पैलेस",
    "panchal": "पांचाल",
    "pankaj": "पंकज",
    "paper": "पेपर",
    "parinay": "परिणय",
    "parmar": "परमार",
    "parth": "पार्थ",
    "patel": "पटेल",
    "patidar": "पाटीदार",
    "patrika": "पत्रिका",
    "payal": "पायल",
    "perfect": "परफेक्ट",
    "photo": "फोटो",
    "photocopy": "फोटोकॉपी",
    "plaza": "प्लाज़ा",
    "point": "पॉइंट",
    "pooja": "पूजा",
    "pragati": "प्रगति",
    "pragya": "प्रज्ञा",
    "prajapati": "प्रजापति",
    "prakashan": "प्रकाशन",
    "prasad": "प्रसाद",
    "press": "प्रेस",
    "prince": "प्रिंस",
    "print": "प्रिंट",
    "printer": "प्रिंटर",
    "printers": "प्रिंटर्स",
    "printing": "प्रिंटिंग",
    "priya": "प्रिया",
    "publication": "पब्लिकेशन",
    "publications": "पब्लिकेशन्स",
    "pustak": "पुस्तक",
    "pvt": "प्राइवेट",
    "rahul": "राहुल",
    "raj": "राज",
    "rajesh": "राजेश",
    "rajkumar": "राजकुमार",
    "rakesh": "राकेश",
    "ram": "राम",
    "ramdev": "रामदेव",
    "ramesh": "रमेश",
    "rathore": "राठौड़",
    "road": "रोड",
    "rohit": "रोहित",
    "royal": "रॉयल",
    "rudra": "रुद्र",
    "sachin": "सचिन",
    "sadan": "सदन",
    "sagar": "सागर",
    "sahayog": "सहयोग",
    "sai": "साईं",
    "salasar": "सालासर",
    "sales": "सेल्स",
    "samiti": "समिति",
    "sanjay": "संजय",
    "sanstha": "संस्था",
    "saraswati": "सरस्वती",
    "satish": "सतीश",
    "sawariya": "सांवरिया",
    "screen": "स्क्रीन",
    "service": "सर्विस",
    "services": "सर्विसेज",
    "seva": "सेवा",
    "shadi": "शादी",
    "shakti": "शक्ति",
    "shankar": "शंकर",
    "sharda": "शारदा",
    "sharma": "शर्मा",
    "shiv": "शिव",
    "shivam": "शिवम",
    "shop": "शॉप",
    "shree": "श्री",
    "shri": "श्री",
    "shubh": "शुभ",
    "shubham": "शुभम",
    "shyam": "श्याम",
    "sisodiya": "सिसोदिया",
    "solanki": "सोलंकी",
    "soni": "सोनी",
    "sons": "सन्स",
    "sri": "श्री",
    "stationery": "स्टेशनरी",
    "stationary": "स्टेशनरी",
    "store": "स्टोर",
    "stores": "स्टोर्स",
    "studio": "स्टूडियो",
    "subham": "शुभम",
    "sumit": "सुमित",
    "sunil": "सुनील",
    "suresh": "सुरेश",
    "swami": "स्वामी",
    "telecom": "टेलीकॉम",
    "traders": "ट्रेडर्स",
    "trading": "ट्रेडिंग",
    "trust": "ट्रस्ट",
    "umesh": "उमेश",
    "unique": "यूनिक",
    "vaishno": "वैष्णो",
    "vijay": "विजय",
    "vinayak": "विनायक",
    "vishal": "विशाल",
    "works": "वर्क्स",
    "world": "वर्ल्ड",
    "xerox": "ज़ेरॉक्स",
    "yadav": "यादव",
    "yash": "यश",
    "aalot": "आलोट",
    "adinath": "आदिनाथ",
    "nath": "नाथ",
    "narayan": "नारायण",
    "narayana": "नारायण",
}

# City spellings used on the sticker. The key is the stored English name, folded.
CITIES = {
    "aaron": "एरोन",
    "abdullaganj": "अब्दुल्लागंज",
    "agar": "आगर",
    "agra": "आगरा",
    "ajmer": "अजमेर",
    "akhodiya mandi": "अखोड़िया मंडी",
    "aklera": "अकलेरा",
    "akluj": "अकलुज",
    "akola": "अकोला",
    "akrela": "अकरेला",
    "alirajpur": "अलीराजपुर",
    "amalner": "अमलनेर",
    "amjera": "अमझेरा",
    "amrawati": "अमरावती",
    "amreli": "अमरेली",
    "anand": "आनंद",
    "anas (dahod)": "अनास (दाहोद)",
    "anjad": "अंजाड़",
    "anjan gav": "अंजन गाँव",
    "ashta": "आष्टा",
    "asnawar": "असनावर",
    "aurangabad": "औरंगाबाद",
    "awalda (gandhwani road)": "आवलदा (गंधवानी रोड)",
    "baag": "बाग",
    "babai": "बबई",
    "bada borgaw": "बड़ा बोरगाँव",
    "badnawar": "बदनावर",
    "badwani": "बड़वानी",
    "bagdi": "बागड़ी",
    "bagli": "बागली",
    "bajna": "बाजना",
    "bakaner": "बकानेर",
    "bakani": "बकानी",
    "bamaniya": "बामनिया",
    "bankhedi": "बाँखेड़ी",
    "banswada": "बांसवाड़ा",
    "barmandal": "बरमांडल",
    "barnagar": "बरनगर",
    "barod": "बड़ौद",
    "barotha": "बरोठा",
    "baru phatak": "बाड़ू फाटक",
    "barwah": "बड़वाह",
    "bedia": "बेदिया",
    "begusarai": "बेगूसराय",
    "bercha": "बेरछा",
    "betma": "बेतमा",
    "betul": "बैतूल",
    "bhabra": "भाबरा",
    "bhanpura": "भानपुरा",
    "bhatpachlana": "भटपचलाना",
    "bhavnagar": "भावनगर",
    "bhawani mandi": "भवानी मंडी",
    "bhesdehi": "भेसदेही",
    "bhesola chopati": "भेसोला चौपाटी",
    "bhikangaon": "भीकनगाँव",
    "bhilai": "भिलाई",
    "bhilwara": "भीलवाड़ा",
    "bhonrasa": "भोंरासा",
    "bhopal": "भोपाल",
    "bid": "बीद",
    "bid (mundi)": "बीद (मुंडी)",
    "bidwal": "बिदवाल",
    "bijalpur": "बिजालपुर",
    "bijepur betma": "बिजेपुर बेतमा",
    "bikaner": "बीकानेर",
    "binaganj": "बीनागंज",
    "biora": "ब्यावरा",
    "birmawal": "बिरमावल",
    "bombay cards": "बॉम्बे कार्ड्स",
    "borgaon bujurg": "बोरगाँव बुजुर्ग",
    "burhanpur": "बुरहानपुर",
    "chandravati": "चंद्रावती",
    "chanera": "चनेरा",
    "chapiheda": "चापीहेड़ा",
    "chapra": "छपरा",
    "chhatkala": "छतकला",
    "chicholi": "चिचोली",
    "chirakhan": "चिराखान",
    "chitodgarh": "चित्तौड़गढ़",
    "chota bairasia": "छोटा बैरसिया",
    "chota udaipur": "छोटा उदयपुर",
    "dag": "डाग",
    "dahhi": "दही",
    "dahod": "दाहोद",
    "dakachia": "डकाछिया",
    "dakachiya": "डकाछिया",
    "dasai": "दसाई",
    "dasai dhar": "दसाई धार",
    "dehri": "डेहरी",
    "depalpur": "देपालपुर",
    "dewas": "देवास",
    "dhamnaud": "धमनौद",
    "dhani": "ढाणी",
    "dhannad": "धन्नाद",
    "dhar": "धार",
    "dhar road": "धार रोड",
    "dharad": "धाराद",
    "dharampuri": "धरमपुरी",
    "dhargaon": "धारगाँव",
    "dhaturia": "धतूरिया",
    "dhule": "धुले",
    "dhuliya": "धुलिया",
    "dodwa": "डोडवा",
    "dongargaon": "डोंगरगाँव",
    "double chowki": "डबल चौकी",
    "dunawa": "दुनवा",
    "dungarpur": "डूंगरपुर",
    "durg": "दुर्ग",
    "gadarwada": "गडरवाड़ा",
    "gandhwani": "गंधवानी",
    "gangapur": "गंगापुर",
    "ganjbasoda": "गंजबासौदा",
    "gautampura": "गौतमपुरा",
    "ghatabillod": "घाटाबिल्लोद",
    "ghatoli": "घाटोली",
    "gogava": "गोगावा",
    "gotegaon": "गोटेगाँव",
    "gujri": "गुजरी",
    "guna": "गुना",
    "harangaon": "हरनगाँव",
    "harda": "हरदा",
    "hatod": "हातोद",
    "hatpipliya": "हाटपिपलिया",
    "hoshangabad": "होशंगाबाद",
    "hyderabad": "हैदराबाद",
    "indore": "इंदौर",
    "itarsi": "इटारसी",
    "jaisehpura": "जयसिंहपुरा",
    "jamnagar": "जामनगर",
    "jaora": "जावरा",
    "jeerapur": "जीरापुर",
    "jeerawad": "जीरावद",
    "jhabua": "झाबुआ",
    "jhaknawada": "झकनवाड़ा",
    "jhalawad": "झालावाड़",
    "jhalrapatan": "झालरापाटन",
    "jobat": "जोबट",
    "jodhpur": "जोधपुर",
    "jolana": "जोलाना",
    "juni kaserabakhal": "जुनी कसेराबखल",
    "kaalmukhi": "कालमुखी",
    "kakroli": "काकरोली",
    "kalapipal": "कालापीपल",
    "kalidevi": "कालीदेवी",
    "kalyanpura": "कल्याणपुरा",
    "kanad": "कनाद",
    "kannod": "कन्नौद",
    "kanvan": "कनवान",
    "karai": "कराई",
    "kareli": "करेली",
    "karera": "करैरा",
    "karod": "करौद",
    "karodkala": "करौदकला",
    "karoli (manawar)": "करोली (मनावर)",
    "kasrawad": "कसरावद",
    "kataphord": "काटाफोर्ड",
    "katkut": "कटकुट",
    "kesur": "केसूर",
    "khalghat": "खलघाट",
    "khalwa": "खलवा",
    "khandwa": "खंडवा",
    "khar (khalwa)": "खर (खलवा)",
    "khargone": "खरगोन",
    "kharotia": "खारोटिया",
    "khategaon": "खातेगाँव",
    "khawasa": "खवासा",
    "khilchipur": "खिलचीपुर",
    "khujner": "खुजनेर",
    "kodriya mhow": "कोडरिया महू",
    "kolhapur": "कोल्हापुर",
    "kota": "कोटा",
    "kshipra": "क्षिप्रा",
    "kukshi": "कुक्षी",
    "kundanpur": "कुंदनपुर",
    "kurawar": "कुरावर",
    "kushalgarh": "कुशलगढ़",
    "labriya": "लबरिया",
    "lateri": "लटेरी",
    "loharda": "लोहार्दा",
    "lohari": "लोहारी",
    "machalpur": "माचलपुर",
    "madhusudangarh": "मधुसूदनगढ़",
    "mahasamund": "महासमुंद",
    "maheshwar": "महेश्वर",
    "mahidpur": "महिदपुर",
    "makdon": "मकडोन",
    "makshi": "मकसी",
    "maksi": "माकसी",
    "manawar": "मनावर",
    "mandi": "मंडी",
    "mandleshwar": "मंडलेश्वर",
    "mandsaur": "मंदसौर",
    "mangliya": "मंगलिया",
    "manohar thana": "मनोहर थाना",
    "manoharthana": "मनोहरथाना",
    "manpur": "मानपुर",
    "meghnagar": "मेघनगर",
    "mhow": "महू",
    "mohanbadodiya": "मोहनबड़ौदिया",
    "morbi": "मोरबी",
    "mukta nagar": "मुक्ता नगर",
    "multai": "मुलताई",
    "mumbai": "मुंबई",
    "mundi": "मुंडी",
    "musakhedi": "मूसाखेड़ी",
    "nagda (dhar)": "नागदा (धार)",
    "nagda (jn)": "नागदा (जंक्शन)",
    "nagpur": "नागपुर",
    "nalcha": "नलछा",
    "nalkheda": "नालखेड़ा",
    "namli": "नामली",
    "nanded": "नांदेड़",
    "narmadapuram": "नर्मदापुरम",
    "narsinghgarh": "नरसिंहगढ़",
    "narsinghpur": "नरसिंहपुर",
    "narsullaganj": "नरसुल्लागंज",
    "nasirabad": "नसीराबाद",
    "neemuch": "नीमच",
    "nemawar": "नेमावर",
    "nepanagar": "नेपानगर",
    "nisarpur": "निसरपुर",
    "obedullaganj": "ओबेदुल्लागंज",
    "pachora": "पचोरा",
    "pachore": "पचोर",
    "padhana": "पधाणा",
    "palas": "पलास",
    "paliya": "पालिया",
    "palyamata": "पल्यामाता",
    "pansemal": "पानसेमल",
    "para": "पारा",
    "parasia": "परासिया",
    "parbhani": "परभणी",
    "petlawad": "पेटलावद",
    "pidawa": "पिड़ावा",
    "pipal gon": "पीपल गाँव",
    "pipalkheda": "पीपलखेड़ा",
    "pipalrawa": "पीपलरावा",
    "pipariya": "पिपरिया",
    "pipliya mandi": "पिपलिया मंडी",
    "pipri": "पिपरी",
    "pithampur": "पीथमपुर",
    "polai kala": "पोलाई कला",
    "pratapgarh": "प्रतापगढ़",
    "punasa": "पुनासा",
    "pune": "पुणे",
    "punjapura": "पंजापुरा",
    "raaver": "रावेर",
    "rain mhow, fanta": "रैन महू, फांटा",
    "raipur": "रायपुर",
    "raipuria": "रायपुरिया",
    "raipuria (jhabua)": "रायपुरिया (झाबुआ)",
    "rajgarh": "राजगढ़",
    "rajgarh (biora)": "राजगढ़ (ब्यावरा)",
    "rajgarh (dhar)": "राजगढ़ (धार)",
    "rajhot": "राजहोट",
    "rajkot": "राजकोट",
    "rajpur": "राजपुर",
    "ramganj mandi": "रामगंज मंडी",
    "ramgarh": "रामगढ़",
    "ranapur": "रानापुर",
    "ranchi": "रांची",
    "ratlai": "रतलाई",
    "ratlam": "रतलाम",
    "rau": "राऊ",
    "rewa": "रीवा",
    "sadalpur": "सादलपुर",
    "sadora": "सदोरा",
    "sagor": "सागर",
    "sahada": "शहादा",
    "saikheda": "साईखेड़ा",
    "sailana": "सैलाना",
    "sanawad": "सनावद",
    "sandawata": "सांडवता",
    "sannod": "सन्नोद",
    "sanwer": "सांवेर",
    "sarangi": "सारंगी",
    "sarangpur": "सारंगपुर",
    "sardarpur": "सरदारपुर",
    "sarothi": "सरोठी",
    "satna": "सतना",
    "satwas": "सतवास",
    "sehore": "सीहोर",
    "semlauda": "सेमलौदा",
    "sendhwa": "सेंधवा",
    "seoni malwa": "सिवनी मालवा",
    "shadura": "शादुरा",
    "shajapur": "शाजापुर",
    "shivgadh": "शिवगढ़",
    "shivpuri": "शिवपुरी",
    "shujalpur": "शुजालपुर",
    "shyampura": "श्यामपुरा",
    "simrol": "सिमरोल",
    "singhana": "सिंघना",
    "sirohi": "सिरोही",
    "sirpur": "सिरपुर",
    "sonkach": "सोनकच्छ",
    "sonkash": "सोनकच्छ",
    "soyatkala": "सोयतकला",
    "sukrawasa": "सुकरवासा",
    "surani": "सुरानी",
    "surat": "सूरत",
    "susner": "सुसनेर",
    "suthaliya": "सुथलिया",
    "taanda": "टांडा",
    "tablai": "तबलाई",
    "takipura": "टाकीपुरा",
    "talwada deb": "तलवाड़ा देब",
    "tanda": "टांडा",
    "tanodiya": "तनोदिया",
    "tappa": "टप्पा",
    "tarana": "ताराना",
    "thandla": "थंदला",
    "thikri": "ठीकरी",
    "tilgara": "तिलगढ़",
    "tonk khurd": "टोंक खुर्द",
    "udaipur": "उदयपुर",
    "udaipura": "उदयपुरा",
    "udaygarh": "उदयगढ़",
    "ujjain": "उज्जैन",
    "ullasnagar": "उल्हासनगर",
    "umarban": "उमरबान",
    "unhel": "उनहेल",
    "vidisa": "विदिशा",
    "yavatmal": "यवतमाल",
}

_VOWELS = (
    ("aa", "ा", "आ"),
    ("ai", "ै", "ऐ"),
    ("au", "ौ", "औ"),
    ("ee", "ी", "ई"),
    ("ii", "ी", "ई"),
    ("oo", "ू", "ऊ"),
    ("uu", "ू", "ऊ"),
    ("ou", "ौ", "औ"),
    ("a", "", "अ"),
    ("e", "े", "ए"),
    ("i", "ि", "इ"),
    ("o", "ो", "ओ"),
    ("u", "ु", "उ"),
)
_CONS = (
    ("ksh", "क्ष"),
    ("chh", "छ"),
    ("kh", "ख"),
    ("gh", "घ"),
    ("th", "थ"),
    ("dh", "ध"),
    ("ph", "फ"),
    ("bh", "भ"),
    ("jh", "झ"),
    ("sh", "श"),
    ("ch", "च"),
    ("k", "क"),
    ("g", "ग"),
    ("c", "क"),
    ("j", "ज"),
    ("t", "त"),
    ("d", "द"),
    ("n", "न"),
    ("p", "प"),
    ("b", "ब"),
    ("m", "म"),
    ("y", "य"),
    ("r", "र"),
    ("l", "ल"),
    ("v", "व"),
    ("w", "व"),
    ("h", "ह"),
    ("f", "फ"),
    ("z", "ज़"),
    ("q", "क"),
    ("x", "क्स"),
    ("s", "स"),
)
_PARTS = re.compile(r"[A-Za-z]+|\d+|\s+|[^A-Za-z0-9\s]+")


def _city_key(name: str) -> str:
    s = (name or "").strip().lower()
    s = re.sub(r"\s+", " ", s)
    s = re.sub(r"\s*,\s*", ", ", s)
    s = re.sub(r"\(\s*", "(", s)
    s = re.sub(r"\s*\)", ")", s)
    return s.strip()


def _phonetic(word: str) -> str:
    s = word.lower()
    i = 0
    out: list[str] = []
    pending: str | None = None
    n = len(s)

    def flush() -> None:
        nonlocal pending
        if pending is not None:
            out.append(pending)
            pending = None

    while i < n:
        rest = s[i:]
        if rest.startswith("aya"):
            if pending is not None:
                out.append(pending + "ा")
                out.append("य")
                pending = None
            else:
                out.append("आय")
            i += 3
            continue
        if rest.startswith("ah") and i + 2 == n and pending is not None:
            out.append(pending + "ाह")
            pending = None
            i += 2
            continue
        matched = False
        for seq, matra, indep in _VOWELS:
            if not rest.startswith(seq):
                continue
            at_end = i + len(seq) == n
            if seq == "a" and pending is not None:
                nxt = s[i + 1 :]
                if len(nxt) == 1 and nxt.isalpha() and nxt not in "aeiou":
                    out.append(pending + "ा")
                    pending = None
                    i += 1
                    matched = True
                    break
                if at_end:
                    out.append(pending + "ा")
                    pending = None
                    i += 1
                    matched = True
                    break
                out.append(pending)
                pending = None
                i += 1
                matched = True
                break
            if seq == "i" and at_end and pending is not None:
                out.append(pending + "ी")
                pending = None
                i += 1
                matched = True
                break
            if pending is not None:
                out.append(pending + matra if matra else pending)
                pending = None
            else:
                out.append(indep)
            i += len(seq)
            matched = True
            break
        if matched:
            continue
        for seq, cons in _CONS:
            if not rest.startswith(seq):
                continue
            if pending is not None:
                out.append(pending + "्")
            pending = cons
            i += len(seq)
            matched = True
            break
        if matched:
            continue
        flush()
        out.append(s[i])
        i += 1
    flush()
    return "".join(out)


def _word(token: str) -> str:
    key = token.lower()
    if key in WORDS:
        return WORDS[key]
    if len(key) <= 2:
        return token.upper()
    return _phonetic(key)


def hindi_name(text: str) -> str:
    if not (text or "").strip():
        return ""
    parts = _PARTS.findall(text)
    return "".join(_word(p) if p.isalpha() else p for p in parts)


def hindi_city(text: str) -> str:
    key = _city_key(text)
    if not key:
        return ""
    hit = CITIES.get(key)
    if hit:
        return hit
    return hindi_name(text)
